// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('create post', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  it('create post', async function() {
    await driver.get("http://localhost:8080/login")
    await driver.manage().window().setRect({ width: 799, height: 775 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("password")).sendKeys("5asgCVdTdxEN8QY")
    await driver.findElement(By.id("username")).sendKeys("User1")
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("title")).click()
    await driver.findElement(By.id("title")).sendKeys("Title")
    await driver.findElement(By.id("description")).click()
    await driver.findElement(By.id("description")).sendKeys("Description")
    await driver.findElement(By.id("body")).click()
    await driver.findElement(By.id("body")).sendKeys("Body")
    await driver.findElement(By.id("author")).click()
    await driver.findElement(By.id("author")).sendKeys("User1@User1.User1")
    await driver.findElement(By.id("post")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.id("log_out")).click()
    await driver.findElement(By.css(".container")).click()
    await driver.close()
  })
})
