// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  it('login', async function() {
    await driver.get("http://localhost:8080/login")
    await driver.manage().window().setRect({ width: 799, height: 775 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("User1")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("5asgCVdTdxEN8QY")
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.css(".footer-copyright")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.id("log_out")).click()
    await driver.findElement(By.css(".container")).click()
    await driver.close()
  })
})
