// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('profile', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  it('profile', async function() {
    await driver.get("http://localhost:8080/login")
    await driver.manage().window().setRect({ width: 799, height: 775 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("password")).sendKeys("5asgCVdTdxEN8QY")
    await driver.findElement(By.id("username")).sendKeys("User1")
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.id("profile")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("User1@User1.User1")
    await driver.findElement(By.id("firstname")).click()
    await driver.findElement(By.id("firstname")).sendKeys("Name")
    await driver.findElement(By.id("lastname")).click()
    await driver.findElement(By.id("lastname")).sendKeys("LName")
    await driver.findElement(By.id("age")).click()
    await driver.findElement(By.id("age")).sendKeys("25")
    await driver.findElement(By.id("notActive_Male")).click()
    await driver.findElement(By.id("address")).click()
    await driver.findElement(By.id("address")).sendKeys("Konotop")
    await driver.findElement(By.id("website")).click()
    await driver.findElement(By.id("website")).sendKeys("https://www.mongodb.com")
    await driver.findElement(By.id("update_profile")).click()
    await driver.findElement(By.css("body")).click()
    await driver.findElement(By.id("log_out")).click()
    await driver.findElement(By.css(".container")).click()
    await driver.close()
  })
})
